version: 2
jobs:
  build:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: bin/build_and_push
workflows:
  version: 2
  build:
    triggers:
       - schedule:
           cron: "0 0 * * *"
           filters:
             branches:
               only: master
    jobs:
      - build:
          filters:
            branches:
              only: master
